### PR TITLE
Use latest Read the Docs build image

### PR DESCRIPTION
**Pull request by humitos**
- Use latest Ubuntu image available
- Use latest Python version

> I'm using this PR as a way to debug #27 as well.

### CODE REVIEW

**Comment by cjw296** [comment]
`python -mvirtualenv /home/docs/checkouts/...` - where does that `virtualenv` come from?
Surprised it's not `venv`, but it's the only difference I can spot so far, although I'd be surprised if it made a difference...

I really wish we could get a "local reproducer" for this, but my efforts so far have failed :-/

**Comment by humitos** [comment]
@cjw296 I added a `tree` command to understand the structure and list all the files in the virtualenv (see https://readthedocs.org/projects/mailinglogger/builds/18436647/)

I'm sure this is a problem with the package itself because the `version.txt` file does not end up inside the virtualenv at `python3.10/site-packages/mailinglogger/`. Then when the module is imported, it fails, since it tries to read the file from there.

I don't know _why_ this happens, tho. It may be a different version of `pip`, `setuptools`, or similar 🤷🏼

**Comment by cjw296** [comment]
@humitos - looks like whatever it is in readthedocs build environment and method of installation doesn't pick up `setuptools-git`'s stuff found with `include_package_data=True`.

It's easier to just drop the use of `setuptools-git` in my case, so that's what I've done in https://github.com/simplistix/mailinglogger/pull/27.

Might be worth adding to docs somewhere that `setuptools-git` doesn't work with RTD?

Anyway, thankyou very much for your help with this!

**Comment by humitos** [comment]
Excellent! I'm happy that you found the issue and solved it already. I didn't see that `setuptools-git` was being used when building the package, but I also wasn't aware what it did 😄 

> Might be worth adding to docs somewhere that `setuptools-git` doesn't work with RTD?

I don't understand why Read the Docs wouldn't make usage of `setuptools-git`; but it's clear that there is a difference here between the local and the RTD environment. If you want to collaborate by adding a small mention about this, the FAQ is probably a good place to do it: https://docs.readthedocs.io/en/latest/faq.html

**Pull request closed without merging**
